### ISSUE TITLE
How to show server info?

### ISSUE THREAD

**Issue by JohnnyWoong** [MiraWaNeko/DiscordIntegration#154] opened 2018-06-04 14:41 UTC
How to show server info just like that

![qq 20180604224029](https://user-images.githubusercontent.com/5661094/40923838-69160342-6848-11e8-83ec-97e923e1a30c.png)

**Comment by Mijago** [comment] 2018-06-04 14:44
Fun Fact: I am implementing this exactly at this moment.

So you can not do this *yet*, but you can do it soon.

**Comment by MiraWaNeko** [comment] 2018-06-04 14:45
Duplicate of #134

**Closed as completed by MiraWaNeko** 2018-06-04 14:45 UTC
Labels: duplicate

**Comment by JohnnyWoong** [comment] 2018-06-05 00:58
Nice to hear than,hope can use it in soon,thx :)
