### ISSUE TITLE
Discord categories

### ISSUE THREAD

**Issue by topher2010** [MiraWaNeko/DiscordIntegration#90] opened 2017-09-23 03:30 UTC
### Base informations
**Minecraft version:**
all versions
**DiscordIntegration version:**
Latest
**Link to pastebin with (censored) config:** *Optional*

### Expected behavior
Relay chat between discord and Minecraft
### Actual behavior
When channels are put into categories on Discord, DiscordItegration stops relaying chat between the two.

**Comment by jc2xs** [comment] 2017-09-23 15:26
I'll second this one.  I have two MC 1.12 forge servers that stopped communicating to discord.  The only change was moving the channel into a group on the discord server.  The MC 1.10 forger server I have that is running Discord Integration 2.1.0 is working fine.  So this only impacts the new 3.x version of Discord Integration.

**Comment by Inrixia** [comment] 2017-09-24 01:39
@topher2010 and @jc2xs For more detail and a Fix look here: https://github.com/Chikachi/DiscordIntegration/issues/91

**Comment by jc2xs** [comment] 2017-09-30 03:00
I can confirm this was fixed in 3.0.3.  So this issue can be closed.

**Comment by Inrixia** [comment] 2017-09-30 03:04
@jc2xs 3.0.3 has been crashing on load for us re issue https://github.com/Chikachi/DiscordIntegration/issues/91 what mc version are you running for 3.0.3 and does your config differ from the one I have posted (for 3.0.2) in issue https://github.com/Chikachi/DiscordIntegration/issues/91

**Comment by jc2xs** [comment] 2017-09-30 03:37
I'm running two servers.  

forge-1.12.2-14.23.0.2489-universal  VoxelVerse
forge-1.12.1-14.22.1.2485-universal  ATM3

As for the configs they are identical except the bot and channel info.  You can see my config at https://pastebin.com/tnju1w0y

**Comment by Inrixia** [comment] 2017-09-30 03:43
@jc2xs Ah, pretty sure that 3.0.3 crashes on 1.7.10 or 1.10 or both... I might test it later though.

**Comment by jc2xs** [comment] 2017-09-30 03:44
Haven't tried it on that version.  My 1.10 seems to be running fine on a 2.1.0 of Discord Integration.

**Comment by Inrixia** [comment] 2017-09-30 03:46
@jc2xs We were running 2.1.0 but updated recently. 3.0.2 works fine for 1.10 though. However for 1.7.10 there are a bunch of issues with categories and other stuff that's mentioned here https://github.com/Chikachi/DiscordIntegration/issues/92

**Closed as completed** 2017-10-07 22:21 UTC
