### ISSUE TITLE
Command results to "Unknown Command"

### ISSUE THREAD

**Issue by Klaga** [MiraWaNeko/DiscordIntegration#138] opened 2018-04-09 09:29 UTC
### Base informations
**Minecraft version:*1.7.10*

**DiscordIntegration version:3.0.5

**Link to pastebin with (censored) config:** *Optional*
http://pasted.co/48569c67

### Expected behavior
When i use !troll it runs the command and either bans / mutes / kills the player selected after.

### Actual behavior
"Returns with Unknown command. Try /help for a list of commands"
(Tried Kill, Tempban, Ban, mute, list & kill, with {ARGS} and a name)

### Steps to reproduce
Add the commands above to the discord command config.

**Comment by MiraWaNeko** [comment] 2018-04-09 09:38
Which server type and version? (Forge/Spigot/Sponge)

**Comment by Klaga** [comment] 2018-04-09 09:50
Modded MC, so forge, believe were using a verison of thermos as launch jar. Running the 1.7.10 pack from technic.
EDIT:
Thermos Version: cyberdynecc:Thermos:1.7.10-1614.58
Forge Version: 10.13.4.1614

**Comment by Mijago** [comment] 2018-06-06 06:28
Duplicate of #137

**Closed as completed by Mijago** 2018-06-06 06:28 UTC
Labels: investigating
