### ISSUE TITLE
Can't handle Discord categories.

### ISSUE THREAD

**Issue by Tokeli** [MiraWaNeko/DiscordIntegration#124] opened 2018-01-14 08:55 UTC
### Base informations
**Minecraft version:**
1.12.2
**DiscordIntegration version:**
1.12-3.0.2
**Link to pastebin with (censored) config:** *Optional*

### Expected behavior
Mod launches, bot talks.
### Actual behavior
Mod gets an exception, bot never initializes despite being online in Discord.
### Steps to reproduce
Add a Category in Discord. It's that simple. Removing the category allows the bot to work.

Crashlog, even tho it didn't crash:
```
[03:55:01] [JDA MainWS-ReadThread/INFO] [STDERR]: [chikachi.discord.repack.net.dv8tion.jda.core.utils.SimpleLog:print:396]: [03:55:01] [Fatal] [JDASocket]: Received a channel for a guild that isn't a text or voice channel. JSON: {"permission_overwrites":[],"nsfw":false,"parent_id":null,"name":"Swolozone","bitrate":64000,"position":0,"id":"123459751000293058","user_limit":0,"type":4}
[03:55:01] [JDA MainWS-ReadThread/INFO] [STDERR]: [chikachi.discord.repack.net.dv8tion.jda.core.utils.SimpleLog:print:396]: [03:55:01] [Fatal] [JDASocket]: Received a channel for a guild that isn't a text or voice channel (ChannelPass). JSON: {"permission_overwrites":[],"nsfw":false,"parent_id":null,"name":"Swolozone","bitrate":64000,"position":0,"id":"123459751000293058","user_limit":0,"type":4}
[03:55:01] [JDA MainWS-ReadThread/INFO] [STDERR]: [chikachi.discord.repack.net.dv8tion.jda.core.utils.SimpleLog:print:396]: [03:55:01] [Fatal] [JDASocket]: Encountered an exception:
[03:55:01] [JDA MainWS-ReadThread/INFO] [STDERR]: [chikachi.discord.repack.net.dv8tion.jda.core.utils.SimpleLog:print:396]: [03:55:01] [Fatal] [JDASocket]: java.lang.RuntimeException: Got permission_override for unknown channel with id: 123459751000293058
        at chikachi.discord.repack.net.dv8tion.jda.core.entities.EntityBuilder.createGuildChannelPass(EntityBuilder.java:398)
        at chikachi.discord.repack.net.dv8tion.jda.core.entities.EntityBuilder.createGuildFirstPass(EntityBuilder.java:285)
        at chikachi.discord.repack.net.dv8tion.jda.core.handle.GuildCreateHandler.handleInternally(GuildCreateHandler.java:38)
        at chikachi.discord.repack.net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
        at chikachi.discord.repack.net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:768)
        at chikachi.discord.repack.net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:498)
        at chikachi.discord.repack.net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:801)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at chikachi.discord.repack.com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

```

**Comment by MiraWaNeko** [comment] 2018-01-15 17:24
Duplicate of #87
Issue was fixed in 3.0.3

**Closed as completed by MiraWaNeko** 2018-01-15 17:24 UTC
Labels: duplicate
